blank_issues_enabled: true
contact_links:
  - name: Security problem
    url: https://github.com/Chamanrajragu/purffle-shorts/blob/main/SECURITY.md
    about: Please report security problems privately, as described here.
